export enum AuditActionType {
  LOGIN = 'login',
  LOGOUT = 'logout',
  SURVEY_CREATE = 'survey_create',
  SURVEY_UPDATE = 'survey_update',
  SURVEY_DELETE = 'survey_delete',
  SURVEY_ARCHIVE = 'survey_archive',
  QUESTION_CREATE = 'question_create',
  QUESTION_UPDATE = 'question_update',
  QUESTION_DELETE = 'question_delete',
  NOTIFICATION_SENT = 'notification_sent',
  RESPONSE_SUBMIT = 'response_submit',
  DATA_EXPORT = 'data_export',
  ROLE_CHANGE = 'role_change',
  DATA_CLEANUP = 'data_cleanup',
  REWARD_REDEMPTION = 'reward_redemption',
  MANUAL_REWARD_DISTRIBUTION = 'manual_reward_distribution',
  POINT_MANUAL_CREDIT = 'point_manual_credit',
  USER_CREATE = 'user_create',
  USER_UPDATE = 'user_update',
  USER_ACTIVATE = 'user_activate',
  USER_DEACTIVATE = 'user_deactivate',
  USER_PASSWORD_RESET = 'user_password_reset',
  USER_BULK_IMPORT = 'user_bulk_import',
  USER_DELETE = 'user_delete',
}
